sudo: false
language: python
services:
  - redis-server
python:
  - "3.5"
env:
  global:
    - HUEY_REDIS_HOST=localhost
    - DATABASE_URL=postgres://postgres@localhost/func_sig_registry
  matrix:
    - TOX_ENV=py35-django19
    - TOX_ENV=flake8
cache: pip
install:
  - "travis_retry pip install setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - psql -c 'create database func_sig_registry;' -U postgres
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
