language: python
services:
  - redis-server
python:
  - "3.6"
dist: trusty
sudo: required
env:
  global:
    - REDIS_URL=redis://localhost:6379
    - DATABASE_URL=postgres://postgres@localhost/func_sig_registry
  matrix:
    - TOX_ENV=py36-django19
    - TOX_ENV=flake8
cache:
  - pip: true
  - directories:
    - $HOME/.ethash
before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
install:
  - travis_retry sudo apt-get install -y ethereum
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
before_script:
  - psql -c 'create database func_sig_registry;' -U postgres
  - mkdir -p $HOME/.ethash
  - geth makedag 0 $HOME/.ethash
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
