language: python
services:
  - redis-server
python:
  - "3.5"
dist: trusty
sudo: required
env:
  global:
    - REDIS_URL=redis://localhost:6379
    - DATABASE_URL=postgres://postgres@localhost/func_sig_registry
    #- SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.4.2/solc"
  matrix:
    - TOX_ENV=py35-django19
    #- TOX_ENV=py35-contracts
    - TOX_ENV=flake8
cache:
  - pip: true
  - directories:
    - $HOME/.ethash
    #- $TRAVIS_BUILD_DIR/solc-versions/solc-0.4.2
    #- $TRAVIS_BUILD_DIR/solc-versions/solidity-0.4.2/build
before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
install:
  #- ./bin/install_solc-0.4.2.sh
  - travis_retry sudo apt-get install -y ethereum
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
before_script:
  - psql -c 'create database func_sig_registry;' -U postgres
  #- ls -lah $TRAVIS_BUILD_DIR/solc-versions/solc-0.4.2/
  #- ./solc-versions/solc-0.4.2/solc --version
  - mkdir -p $HOME/.ethash
  - geth makedag 0 $HOME/.ethash
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
